package Study.random;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class groupAnagrams {
    /**
     * Group Anagrams
     * Given an array of strings strs, group all anagrams together into sublists.
     * You may return the output in any order.
     * An anagram is a string that contains the exact same characters as another string,
     * but the order of the characters can be different.
     *.
     * Example 1:
     * Input: ["act","pots","tops","cat","stop","hat"]
     * Output: [["hat"],["act", "cat"],["stop", "pots", "tops"]]
     */
    public static void main(String[] args) {
        String[] strs = {"eat", "tea", "tan", "ate", "nat", "bat"};
        String[] strs2 = {"hhhhu","tttti","tttit","hhhuh","hhuhh","tittt"};
        System.out.println("Input: " + Arrays.toString(strs2));
        System.out.println("Output: " + groupAllAnagrams(strs2));
    }

    /**
     * Function to group all anagrams together
     * Store all the anagrams in a hashmap as value and return the values.
     * Let the keys be generated by a logic.
     *
     * @param strs - the array of strings
     * @return - the list of lists of anagrams
     */
    private static List<List<String>> groupAllAnagrams(final String[] strs) {
        HashMap<String, List<String>> map = new HashMap<>();

        // Loop through each string in the array
        for (String str : strs) {
            String key = getKey(str);
            if (!map.containsKey(key)) {
                map.put(key, new ArrayList<>());
            }
            map.get(key).add(str);
        }

        return new ArrayList<>(map.values());
    }

    /**
     * Helper function to generate a key for the anagram.
     * We could have sorted the string and use it as key,
     * but it would not have been efficient
     *
     * @param str - the string to be converted to key
     * @return - the key for the anagram
     */
    private static String getKey(final String str) {
        int[] count = new int[26];
        for (char c : str.toCharArray()) {
            count[c - 'a']++;
        }
        StringBuilder sb = new StringBuilder();
        for (int i : count) {
            sb.append('#');
            sb.append(i);
        }
        return sb.toString();
    }
}
